### ISSUE TITLE
bootstrap-dark-5 overrides rules for list-group-flush

### ISSUE THREAD

**Issue by papjul** [vinorodrigues/bootstrap-dark-5#13]
The following snippet gets overridden by bootstrap-dark-5 `.list-group` rules, i.e. we have borders everywhere instead of having them only on the bottom (except for last child).
https://github.com/twbs/bootstrap/blob/main/scss/_list-group.scss#L146-L156

Also, it's unrelated but `$list-group-bg-alt` is way too dark by default:
![image](https://user-images.githubusercontent.com/1449159/112161147-2177b200-8beb-11eb-98ba-04be41081347.png)

After adding:
`$list-group-bg-alt: transparent`
![image](https://user-images.githubusercontent.com/1449159/112161956-e6c24980-8beb-11eb-810c-4eb717434ff7.png)

And after also adding the missing snippet:
![image](https://user-images.githubusercontent.com/1449159/112161270-4704bb80-8beb-11eb-98b5-5a81b5fc6282.png)

For reference, the default Bootstrap theme:
![image](https://user-images.githubusercontent.com/1449159/112161220-36ecdc00-8beb-11eb-96a1-1fe3e3849e52.png)

And the code to test:
```
<div class="card">
                <div class="card-header"><h5 class="card-title text-center mb-0">Sommaire</h5></div>
                <div class="card-body">
                    <ul class="list-group list-group-flush text-center">
                        <li class="list-group-item"><a href="#opening">Génériques d’ouverture (dits “openings”)</a></li>
                        <li class="list-group-item"><a href="#ending">Génériques de clôture (dits “endings”)</a></li>
                        <li class="list-group-item"><a href="#movie">Génériques de clôture des films</a></li>
                        <li class="list-group-item"><a href="#tv_ost">Bande originale de la série</a></li>
                        <li class="list-group-item"><a href="#movie_ost">Bande originale des films</a></li>
                        <li class="list-group-item"><a href="#other">Autres albums</a></li>
                    </ul>
                </div>
            </div>
```

**Comment by vinorodrigues** [comment]
OK.  I see it.  Blimey!

This is a repercussion of Bootstrap core using named colours for some of their variables.  In the core `_variables.scss` file the value is:
`$list-group-bg: $white !default;`

And when translated to *-dark* became: 
`$list-group-bg-alt: $black !default;`

This giving you the dark list-group.

But that's not where it stops ... also the card background is set as:
`$card-bg: $white !default;`

But in *-dark* I had changed that to:
`$card-bg-alt: mix($gray-800-alt, $gray-900-alt, 50%) !default;`

Yeah ... not very consistent of me - I guess I wanted the card to stand out a bit.

The correction is to make both consistent with the background colour - so:
```scss
$list-group-bg-alt: $gray-900-alt !default;
$card-bg-alt: $gray-900-alt !default;
```
This should give you a more consistent look in comparison to the *-light* original.

![image](https://user-images.githubusercontent.com/366673/112175038-02a90800-8c4b-11eb-983f-cbeddc85094b.png)

Unfortunately - that's not the only component  where `$white` becomes `$black` :(

**Comment by papjul** [comment]
Indeed, it looks better now, however I still have an issue with borders:
![image](https://user-images.githubusercontent.com/1449159/112177479-3eb37d00-8bf9-11eb-9cf1-3e5210dfece1.png)

Can you test with bootstrap-nightshade?

I suppose it comes from `html.dark`.

**Comment by vinorodrigues** [comment]
yes - I see it.

Added following to the `dark\_list-group.scss` file:

```scss
// Flush list items

.list-group-flush {

  > .list-group-item {
    border-width: 0 0 $list-group-border-width;  // needed for nightshade variants

    &:last-child {
      border-bottom-width: 0;
    }
  }
}
```

In the *-nightshade* variant the border width is reset to the original.  This line I removed because I thought it was not needed - but it is.

Good pickup!  Thanks for that.
