### ISSUE TITLE
Bootstrap Night example has wrong styles before using toggle

### ISSUE THREAD

**Issue by theodorejb** [vinorodrigues/bootstrap-dark-5#15]
When I open https://vinorodrigues.github.io/bootstrap-dark-5/ for the first time on Android with dark mode enabled in my browser, the page looks like this:

![Screenshot_20210323-111734__02](https://user-images.githubusercontent.com/3053271/112189954-2841fd00-8bca-11eb-8cca-d23912ea67f0.jpg)

Notice that the table of contents is the wrong color. After I tap the toggle to explicitly enable dark mode, it looks correct:

![Screenshot_20210323-111938__01](https://user-images.githubusercontent.com/3053271/112190109-50316080-8bca-11eb-832a-fc83f6766d9a.jpg)

**Comment by vinorodrigues** [comment]
Good pickup.  JS inside the `cheatsheet-night.html`, line 147, tries to set a const.  Changed the `const` to `var` on line 143.
