### ISSUE TITLE
Feature request: Update / Bootstrap version 5.0.0-beta3 is out!

### ISSUE THREAD

**Issue by dtcooper** [vinorodrigues/bootstrap-dark-5#16]
Hi there. Just opening to represent the feature request of (possibly) updating to 5.0.0-beta3. Thanks!

**Comment by vinorodrigues** [comment]
Jeez!  That came out 1 hour ago.   It's 4:59 AM in Sydney Australia ... I haven't even woken up yet.

**Comment by vinorodrigues** [comment]
btw - source on GitHub is already at β3 ... I just want to run a line for line diff to make sure before I push to NPM.

**Comment by vinorodrigues** [comment]
Okay - it's all good.  Added `accordion-flush` ... the rest is good.  Will push to NPM soon.

**Comment by dtcooper** [comment]
Haha, take your time! Just wanted help put it on your radar. Thanks again. :P

**Comment by dtcooper** [comment]
> I haven't even woken up yet.

You're a very articulate sleep typer. 🙃

**Comment by vinorodrigues** [comment]
v0.1.3 pushed to NPM
