### ISSUE TITLE
[BUG] breadcrumb bg should transparent

### ISSUE THREAD

**Issue by danny007in** [vinorodrigues/bootstrap-dark-5#21]
![image](https://user-images.githubusercontent.com/50356015/118335868-2cd1c480-b52e-11eb-9dcd-ea2306dbc158.png)

Hii @vinorodrigues i am using yours dark method technique (with urs dark scss file) in new AdminLTE v4
So i will report it frequently if bug presents.

**Comment by vinorodrigues** [comment]
Nice spot.  Core sets that to `null` ... meaning SCSS skips generating that css. i.e. `.breadcrumb {  background-color: xxx }` is not generated.

I know I changed it to `$gray-800-alt`, but for the help of me can't remember why.

Reverted this to the `null` - compile the CSS and you should be OK.  Let me know.

**Comment by vinorodrigues** [comment]
oh... and please keep them coming (reporting bugs) ... love the fact that someone else is passionate about this.

**Comment by vinorodrigues** [comment]
assuming as corrected
