### ISSUE TITLE
Unclear instruction for _variables.scss (in the `scss` sub-folder)

### ISSUE THREAD

**Issue by alecpetrosky** [vinorodrigues/bootstrap-dark-5#24]
The instructions state

> Modify `_variables.scss` and `_variables-alt.scss` in the `scss` sub-folder.

`_variables-alt.scss` is indeed present in `scss` sub-folder. However, `_variables.scss` is not.

How can default colors be changed for light variant if afterwards I'd like to use method "4. bootstrap-dark" but with locally compiled css?

**Comment by vinorodrigues** [comment]
As this is a addition to Bootstrap there is an assumption made that you will use this as you would BS itself.  Using the variables file in Bootstrap is assumed … if you need to know how to do that then look to https://getbootstrap.com/docs/5.0/customize/sass/#variable-defaults or do a search on StackOverflow or similar site.

Closing this as not bug related, rather support request that I state in the paper that I will not do.
