### ISSUE TITLE
unwarranted padding change

### ISSUE THREAD

**Issue by techvanity** [vinorodrigues/bootstrap-dark-5#26]
Many thanks for your work.

I noticed an unnecessary padding modification in the dark variants. For example, `bootstrap-nightall.css` contains the following rule
```
.breadcrumb-item + .breadcrumb-item {
  padding-left: 0.5rem;
}
```
Same rule exists in other files too. It is causing some issues for my site since I am working on an RTL project.

Please fix.

**Comment by vinorodrigues** [comment]
Oh... my... how did that get there?   It's removed in commit `bd87428`.   Thanks for the bug report.
