### ISSUE TITLE
Error in method 2 docs

### ISSUE THREAD

**Issue by techvanity** [vinorodrigues/bootstrap-dark-5#27]
As per the readme, method 2 (nightfall) is supposed to use an add-on (color-only) style sheet. But the [quick start page](https://github.com/vinorodrigues/bootstrap-dark-5/blob/main/docs/bootstrap-nightfall.md) for this method still `<link>`s to the full `bootstrap.min.css`.

On a related note, `bootstrap-nightfall.css` is not available in the release zip file (`dist/css` folder). It is available on the CDNs though.

**Comment by vinorodrigues** [comment]
Yes, thank you, well spotted.   Corrected in commit `3d54dfc`.

As to second point - yes, intentional, didn't want people to hotlink to GitHub repo - ZIP is auto-gen by GitHub.
