### ISSUE TITLE
Placeholder on floating labels being shown on nigthshade darkmode

### ISSUE THREAD

**Issue by alexandreapis** [vinorodrigues/bootstrap-dark-5#30]
![floating labels](https://user-images.githubusercontent.com/21248634/125951221-1ecf3a36-b5ed-4b58-b4a3-4302e61c397a.png)

**Comment by trasherdk** [comment]
Maybe you could share on what device / OS / browser you have this experience ??

**Comment by alexandreapis** [comment]
> Maybe you could share on what device / OS / browser you have this experience ??

I'm sorry... It occurs on every browser and OS where I tested, like

Chrome 91 on MacOS Big Sur, Windows 10 and Android 11
Safari on MacOS
Edge on Windows

**Comment by vinorodrigues** [comment]
Yep - I found the bug.  `_floating-labels.scss`, lines 8 - 10:  I had commented out `color: transparent` because in the "-dark" variant it was redundant code.  Seems it is redundant in all except "-nightshade", so adding it back in for all.

**Comment by vinorodrigues** [comment]
thanks for reporting this

**Comment by alexandreapis** [comment]
> thanks for reporting this

thank you for the quick fix and amazing work
