### ISSUE TITLE
Use jsdelivr with NPM instead of GitHub

### ISSUE THREAD

**Issue by Carl-Hugo** [vinorodrigues/bootstrap-dark-5#5]
As by jsdelivr's documentation, I suggest we use NPM as the source instead of GitHub; now that the packages are deployed to NPM.

> We recommend using npm for projects that support it for better UX - npm packages are searchable on our website, and package pages show additional useful information, such as description and link to homepage.

Source: [jsdelivr](https://www.jsdelivr.com/features#gh)

**Comment by vinorodrigues** [comment]
Good one.  I'll do that.

**Comment by vinorodrigues** [comment]
Fixed with [92859a4](https://github.com/vinorodrigues/bootstrap-dark-5/commit/92859a4c9e5de742757292963204773e092a9b61)
