### ISSUE TITLE
Add prefix to restrict classes to light or dark mode

### ISSUE THREAD

**Issue by j-f1** [vinorodrigues/bootstrap-dark-5#50]
It would be great to have a way to limit certain styles to light mode. For example, my navbar looks good in light mode with `.navbar-dark`. However, the dark mode styles do not look as good on top of the background color. Just like there are `.sm-`, `.md-`, etc. prefixes, it would be nice to have `.light-` and `.dark-` (or maybe `.light:`/`.dark:`) prefixes for restricting the relevant styling to only dark mode or non-dark mode.

(I’m currently working around this by copying out the relevant styles, then renaming the class name to something else)

**Comment by vinorodrigues** [comment]
See: https://docs.github.com/en/get-started/quickstart/fork-a-repo

Do that ... then apply your opinions to your heart's content.
