### ISSUE TITLE
Consider a more saturated primary/blue color

### ISSUE THREAD

**Issue by j-f1** [vinorodrigues/bootstrap-dark-5#51]
While the default, desaturated blue color used as blue/primary works well for large surfaces such as buttons, it looks dim and muddy on text (such as `.text-primary` or in links). Would it be possible to make the default blue either more saturated, or override the coloring of blue text to be brighter? Ideally, links in prose would feel more similar in color to the text surrounding them, rather than being de-emphasized.

Perhaps `#43a3f0` for links?

**Comment by vinorodrigues** [comment]
See: https://docs.github.com/en/get-started/quickstart/fork-a-repo

Do that ... then apply your opinions to your heart's content.
