### ISSUE TITLE
Bootstrap 5 utilities broken with bootstrap-unlit

### ISSUE THREAD

**Issue by GoudronViande24** [vinorodrigues/bootstrap-dark-5#52]
The Boostrap 5 utilities are not working with the method 4b, bootstrap-unlit. It does work properly using method 4, boostrap-dark.

I tried making a bootstrap-4-like jumbotron, and it just didn't work.

**Comment by vinorodrigues** [comment]
Bonjour.  You'll need to be more specific.  What in utilities is not working?  Can you give me examples?

**Comment by GoudronViande24** [comment]
On this example : https://getbootstrap.com/docs/5.1/examples/jumbotron/. The jumbotron at the top.
When I use the boostrap-dark, it works, but not with bootstrap-unlit, colors, bg colors and text properties don't work.
I did not test it that much since I could use bootstrap-dark instead and it changes pretty much nothing.

**Comment by vinorodrigues** [comment]
Have a go at it now.

Use the repo `bootstrap-unlit.css` file as the one in NPN is still rel. 1.1.3

If you need to hotlink use: `https://combinatronics.com/vinorodrigues/bootstrap-dark-5/main/dist/css/bootstrap-unlit.css` as I'll only update the rel. when core does.

**Comment by GoudronViande24** [comment]
looks good, added it to my project and it works.
