### ISSUE TITLE
Error at import in React JS

### ISSUE THREAD

**Issue by Anddr3s** [vinorodrigues/bootstrap-dark-5#68]
I'm import bootstrap dark in my sccs file in react js:

`@import '~bootstrap-dark-5/scss/bootstrap-dark.scss';`

But, returns me the next error:

./src/app/assets/scss/formio.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/app/assets/scss/formio.scss)
SassError: File to import not found or unreadable: functions.
        on line 14 of node_modules/bootstrap-dark-5/scss/bootstrap-dark.scss
        from line 3 of /myapp/assets/scss/custom.scss
>> @import "functions";

**Comment by vinorodrigues** [comment]
Did you read the docs on how to import this in React?
