### ISSUE TITLE
.bg-body background color

### ISSUE THREAD

**Issue by max-collomb** [vinorodrigues/bootstrap-dark-5#84]
I noticed that `html.dark .bg-body` has an incorrect background color in the file bootstrap5-nightshade.css : 

`background-color: rgba(var(--bs-body-rgb-alt), var(--bs-bg-opacity)) !important;`

the variable `--bs-body-rgb-alt` doesn't exist. I think it should be `--bs-body-bg-rgb-alt` instead

**Comment by vinorodrigues** [comment]
in the NPM version yes - but the GH code has the correction - see note in issue #80
