### ISSUE TITLE
Trouble including bootstrap-dark-5 scss

### ISSUE THREAD

**Issue by fastloris** [vinorodrigues/bootstrap-dark-5#9]
Hello, I'm trying to use this theme but seeing something a bit strange. In https://github.com/vinorodrigues/bootstrap-dark-5/blob/main/scss/bootstrap-night.scss the includes are fixed, but not included, whereas in https://github.com/vinorodrigues/bootstrap-dark/blob/master/scss/bootstrap-dark.scss they are relative and pull in from the local copy of bootstrap.

The first (-5) is failing because there are no local function files and all the rest. I scanned through the docs and couldn't find anything, have I missed something?

Thanks in advance

**Comment by vinorodrigues** [comment]
Right.  For BS4 I used the relative paths ... as in `../node_modules/bootstrap/scss/**` .. for each include.  *(But that made the files large and I was told wasn't best practice.)*

For BS5 I changed that to injecting that path in the `package.json` file and in it the script that calls the compiler passing it that path.  Like so:

```json
  "css-compile": "sass --style expanded --source-map --embed-sources --no-error-css --load-path=node_modules/bootstrap/scss scss/:dist/css/",
```

Note the `--load-path=` bit.

This way - if you also wanted to add a `variants.scss` file you can.  If yours is there the compiler uses that, if not it uses the BS5 one.  Same for any other file you may want to "override".

You will need to do the same to compile your variants.

**Comment by fastloris** [comment]
Thanks for the pointer!
